name: Translate to Spanish

on:
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: yunwei37/OpenAI-Continuous-Translator@master
      with:
          git_repo_url: https://github.com/digidem/edt-docs
          api_key: ${{ secrets.OPENAI_API_KEY }}
          file_types: "md,mdx"
          source_language: English
          target_language: es
          i18n_surfix: es
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.1
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
