name: Translate to Portuguese

on:
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: digidem/ai-translator-action@main
      with:
          api_key: ${{ secrets.OPENAI_API_KEY }}
          file_types: "md,mdx"
          source_language: English
          target_language: pt-BR
          i18n_surfix: pt
    - name: Branch, Add, Commit & Push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: New AI translation!
        branch: portuguese
        create_branch: true
        file_pattern: '*/**/*.md'
        repository: local_repo
